import React from "react";
import { Typography } from "@mui/material";

export default function TopicDetails() {
  return (
    <div style={{ textAlign: "left", paddingLeft: "2.5%", paddingTop: "1%" }}>
      <Typography sx={{ color: "#00C569", fontSize: "150%" }}>
        Product Details
      </Typography>

      <p>
        Solar energy is any type of energy generated by the sun. Solar energy
        can be harnessed directly or indirectly for human use. These solar
        panels, mounted on a rooftop in Germany, harvest solar energy and
        convert it to electricity. Solar energy is any type of energy generated
        by the sun.
      </p>
    </div>
  );
}
